import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 
import { Toaster } from "sonner";
import Navbar from "@/components/components/NewsNav";
 
import ThemeProvider from "@/components/components/ThemeProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/components/app-sidebar";
import { isAdmin as checkAdmin } from "@/lib/auth/admin";
import { isUser as checkAuthor } from "./actions/getSession";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = await checkAdmin();
  const isAuthor = await checkAuthor();


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <SidebarProvider>
            <AppSidebar isAdmin={isAdmin} isAuthor={isAuthor} />
            <div className="flex flex-col flex-1 w-full min-h-screen">
              <Navbar />
              <main className="flex-1 w-full relative">
                {children}
              </main>
            </div>
          </SidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}